syntax = "proto3";

package meshchat;

message LoginRequest {
  string username = 1;
}

message LoginResponse {
  string username = 1;
}

message CreateChannelRequest {
  string channel_name = 1;
  string requested_by = 2;
}

message CreateChannelResponse {
  string channel_name = 1;
}

message ListChannelsRequest {}

message ListChannelsResponse {
  repeated string channels = 1;
}

message PublishInChannelRequest {
  string channel_name = 1;
  string message = 2;
  string requested_by = 3;
}

message PublishInChannelResponse {
  string channel_name = 1;
  int64 published_timestamp_ms = 2;
}

message ChannelMessageEvent {
  string channel_name = 1;
  string message = 2;
  string sent_by = 3;
  int64 request_timestamp_ms = 4;
  int64 published_timestamp_ms = 5;
  uint64 logical_clock = 6;
}

message ServerInfo {
  string server_name = 1;
  uint32 rank = 2;
}

message RefRegisterServerRequest {
  string server_name = 1;
}

message RefListServersRequest {}

message RefHeartbeatRequest {
  string server_name = 1;
  uint32 rank = 2;
}

message ReferenceRequest {
  int64 timestamp_ms = 1;
  uint64 logical_clock = 2;

  oneof payload {
    RefRegisterServerRequest register_server = 10;
    RefListServersRequest list_servers = 11;
    RefHeartbeatRequest heartbeat = 12;
  }
}

message RefRegisterServerResponse {
  uint32 rank = 1;
}

message RefListServersResponse {
  repeated ServerInfo servers = 1;
}

message RefHeartbeatResponse {
  string status = 1;
}

message ReferenceResponse {
  int64 timestamp_ms = 1;
  uint64 logical_clock = 2;
  bool ok = 3;
  string error_code = 4;
  string error_message = 5;
  int64 reference_timestamp_ms = 6;

  oneof payload {
    RefRegisterServerResponse register_server = 10;
    RefListServersResponse list_servers = 11;
    RefHeartbeatResponse heartbeat = 12;
  }
}

message ClientRequest {
  uint64 request_id = 1;
  int64 timestamp_ms = 2;
  uint64 logical_clock = 3;

  oneof payload {
    LoginRequest login = 10;
    CreateChannelRequest create_channel = 11;
    ListChannelsRequest list_channels = 12;
    PublishInChannelRequest publish_in_channel = 13;
  }
}

message ServerResponse {
  uint64 request_id = 1;
  int64 timestamp_ms = 2;
  uint64 logical_clock = 3;
  bool ok = 4;
  string error_code = 5;
  string error_message = 6;

  oneof payload {
    LoginResponse login = 10;
    CreateChannelResponse create_channel = 11;
    ListChannelsResponse list_channels = 12;
    PublishInChannelResponse publish_in_channel = 13;
  }
}
